/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { ContractEvent, Callback, TransactionObject, BlockType } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class ASK extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): ASK;
  methods: {
    questions(
      arg0: number | string
    ): TransactionObject<{
      questioner: string;
      incentive: string;
      contents: string;
      0: string;
      1: string;
      2: string;
    }>;

    createQuestion(
      _incentive: number | string,
      _meta: string | number[]
    ): TransactionObject<string>;

    getQuestionCount(): TransactionObject<string>;
  };
  events: {
    QuestionCreated: ContractEvent<{
      questioner: string;
      questionID: string;
      0: string;
      1: string;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
